parameters:

services:
    whos_online.listener:
        class: Netpeople\WhosOnlineBundle\Listener\WhosOnlineListener
        arguments: ["@security.context", "@doctrine", "@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: "onKernelRequest" }
            - { name: kernel.event_listener, event: security.interactive_login, method: "onLogin" }
