parameters:
    whos_online.inactive_in: "5 min"
    whos_online.offline_in: "30 min"
    whos_online.clear_in: "2 days"
    
services:
    whos_online:
        class: Netpeople\WhosOnlineBundle\Services\WhosOnline
        arguments: 
             - "@doctrine"
             - "%whos_online.inactive_in%"
             - "%whos_online.offline_in%"
             - "%whos_online.clear_in%"
        
    whos_online.listener:
        class: Netpeople\WhosOnlineBundle\Listener\WhosOnlineListener
        arguments: ["@security.context", "@whos_online", "@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: "onKernelResponse" }
            - { name: kernel.event_listener, event: security.interactive_login, method: "onLogin" }
